AWSTemplateFormatVersion: '2010-09-09'
Description: Random Quotes API Lambda
Resources:
  ApiGatewayApi:
    Properties:
      CacheClusterEnabled: false
      DefinitionBody:
        info:
          title:
            Ref: AWS::StackName
        paths:
          /api/{proxy+}:
            options:
              consumes:
              - application/json
              produces:
              - application/json
              responses:
                '200':
                  description: 200 response
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
                  schema:
                    $ref: '#/definitions/Empty'
              x-amazon-apigateway-integration:
                passthroughBehavior: when_no_match
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                responses:
                  default:
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'''
                      method.response.header.Access-Control-Allow-Methods: '''DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    statusCode: 200
                type: mock
            x-amazon-apigateway-any-method:
              responses: {}
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RandomQuotesAPIFunction.Arn}/invocations
        securityDefinitions:
          randomquotes-cognito-authorizer:
            in: header
            name: Authorization
            type: apiKey
            x-amazon-apigateway-authorizer:
              providerARNs:
              - Fn::GetAtt:
                - UserPool
                - Arn
              type: cognito_user_pools
            x-amazon-apigateway-authtype: cognito_user_pools
        swagger: 2.0
      Name: randomquotes-api
      StageName: prod
    Type: AWS::Serverless::Api
  CognitoIdentityPool:
    Properties:
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders:
      - ClientId:
          Ref: UserPoolClient
        ProviderName:
          Fn::Sub:
          - cognito-idp.us-east-1.amazonaws.com/${UserPoolId}
          - UserPoolId:
              Ref: UserPool
      DeveloperProviderName: randomquotes
      IdentityPoolName: randomquotes
    Type: AWS::Cognito::IdentityPool
  CognitoIdentityPoolRole:
    Properties:
      IdentityPoolId:
        Ref: CognitoIdentityPool
      Roles:
        authenticated:
          Fn::GetAtt:
          - RandomQuotesLambdaRole
          - Arn
        unauthenticated:
          Fn::GetAtt:
          - RandomQuotesLambdaRole
          - Arn
    Type: AWS::Cognito::IdentityPoolRoleAttachment
  QuotesTable:
    Properties:
      PrimaryKey:
        Name: quote
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Type: AWS::Serverless::SimpleTable
  RandomQuotesAPIFunction:
    Properties:
      CodeUri: s3://randomquotes-api/randomquotes-api/a62bdf5f7aaadbb0054e527376b00de0
      Description: Random Quotes API Lambda
      Events:
        GetApiProxyResource:
          Properties:
            Method: any
            Path: /api/{proxy+}
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      FunctionName: randomquotes-api
      Handler: index.handler
      MemorySize: 128
      Policies: AmazonDynamoDBFullAccess
      Role:
        Fn::GetAtt:
        - RandomQuotesLambdaRole
        - Arn
      Runtime: nodejs8.10
      Timeout: 300
    Type: AWS::Serverless::Function
  RandomQuotesLambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Sid: AllowLambdaServiceToAssumeRole
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Path: /
    Type: AWS::IAM::Role
  UserPool:
    Properties:
      AutoVerifiedAttributes:
      - email
      EmailConfiguration:
        ReplyToEmailAddress: dhthong@gmail.com
      EmailVerificationSubject: Welcome to Random Quotes!
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      UserPoolName: RandomquotesPool
    Type: AWS::Cognito::UserPool
  UserPoolClient:
    Properties:
      ClientName: randomquotes-ui
      GenerateSecret: false
      UserPoolId:
        Ref: UserPool
    Type: AWS::Cognito::UserPoolClient
Transform: AWS::Serverless-2016-10-31
